version: "3.8"
services:
  adc-vite-node:
    container_name: adc-vite-node
    build:
      context: .
      dockerfile: ./docker/node/Dockerfile
    volumes:
      - ./:/app
    tty: true
    ports:
      - "3000:3000"
